repos:
  - repo: local
    hooks:
      - id: rust-fmt-clippy-test
        name: fmt, clippy, test
        entry: bash -c 'cargo fmt -- --check && cargo clippy --all-targets -- -D warnings && cargo test'
        language: system
        pass_filenames: false
